lukaszewczak/WDP-2007-02

src/components/common/ProductBox/ProductBox.js, src/components/common/ProductBox/ProductBox.module.scss, src/components/common/ProductBox/ProductBoxContainer.js, src/components/features/NewFurniture/NewFurniture.js, src/redux/productsRedux.js
- Dodałem akcje changeWishlist w produktsRedux odpowiedzialna za zmianę wartości wishlist produktu na przeciwna do poprzedniej lub jeśli jej nie było na true,
- nie dodawałem whishlist do obiektów w initialState.js ponieważ była ona dodawana w innym commicie przez bartosza,
=> Add changeWishlist action in productsRedux and use it in ProductBox

src/components/common/FeatureBox/FeatureBox.js, src/components/common/FeatureBox/FeatureBox.module.scss, src/components/features/FeatureBoxes/FeatureBoxes.js, src/components/features/FeatureBoxes/FeatureBoxes.module.scss
Moreover add links for feature boxes. Links have target blank, could be changed, if client will required it
=> Add hovers on feature boxes

src/components/common/ProductBox/ProductBox.js, src/components/common/ProductBox/ProductBox.module.scss
Dodanie dwoch klas i hover na buttony w css
=> Add class and hover for buttons in ProductBox common

src/components/features/FeatureBoxes/FeatureBoxes.js
Add RVD for FeaturesBoxes
https://projects.kodilla.com/browse/WDP200702-16
=> WDP200702-16

src/components/layout/CompanyClaim/CompanyClaim.js, src/components/layout/CompanyClaim/CompanyClaim.module.scss
Zmiany:
-Liczbę produktów w koszyku umieściłem w paragrafie, na który dodałem padding.
-Problem z wcięciem diva, rozwiązałem zmieniając width na min-width
-Ikonkę koszyka przesunąłem bardziej do lewej strony
=> WDP200702-2

src/components/features/ProductSearch/ProductSearch.js, src/components/features/ProductSearch/ProductSearch.module.scss, src/styles/settings.scss
Dodanie styli i hovera dla select
=> WDP200702-7

src/components/common/Button/Button.module.scss, src/components/common/FeatureBox/FeatureBox.module.scss, src/components/common/ProductBox/ProductBox.module.scss, src/components/features/NewFurniture/NewFurniture.module.scss, src/components/layout/CompanyClaim/CompanyClaim.module.scss, src/components/layout/Footer/Footer.module.scss, src/components/layout/MenuBar/MenuBar.module.scss, src/components/layout/TopBar/TopBar.module.scss, src/styles/settings.scss
https://projects.kodilla.com/secure/RapidBoard.jspa?rapidView=103&projectKey=WDP200702&view=detail&selectedIssue=WDP200702-9
Placeholder  dodany w settingsach,  extendowany hoverowalnych elementach.
Wstępnie czasy animacji 250ms, jesli klient sobie zażyczy zmiany wystaczy dodać kolejne style w settings -> %hover.
=> Add global hover efects

src/components/common/FeatureBox/FeatureBox.module.scss, src/components/common/ProductBox/ProductBox.module.scss, src/components/features/NewFurniture/NewFurniture.module.scss, src/components/layout/CompanyClaim/CompanyClaim.module.scss, src/components/layout/Footer/Footer.module.scss, src/components/layout/MenuBar/MenuBar.module.scss, src/components/layout/TopBar/TopBar.module.scss, src/styles/settings.scss
CEL:
Przyszeregowanie kolorów do zmiennych i później tych zmiennych do komponentów
ZMIANY:
Ustawiłem kolory w pliku Settings.scss i poustawiałem te kolory w komponentach.
LINK JIRA:
https://projects.kodilla.com/browse/WDP200702-8
=> WDP200702-8

src/components/features/ProductSearch/ProductSearch.js, src/components/features/ProductSearch/ProductSearch.module.scss
CEL:
-zamiana komponentu `<select>` na strukturę tworzącą dropdown menu
ZMIANY:
-zamieniłem komponent `<select>` na strukturę `<ul>``<li>``<ul>``<li>` w pliku ProductSearch.js
-dodałem przykładowe kategorie `Category...` do późniejszej zmiany
-do powyższej struktury, stworzyłem style CSS w pliku ProductSearch.module.scss
-w tym samym pliku poprawiłem style dla ikonek w `divie` o klasie `category`
LINK DO JIRA:
https://projects.kodilla.com/browse/WDP200702-10
=> WDP200702-10

src/components/common/ProductBox/ProductBox.module.scss
Poprawiłem hover tak, żeby Buttony  "Quick view" oraz "Add to cart" i tło ceny zmieniało się jednocześnie na hover karty produktu
=> WDP200702-45

src/components/common/ProductBox/ProductBox.module.scss, src/components/features/NewFurniture/NewFurniture.js, src/components/features/NewFurniture/NewFurniture.module.scss, src/styles/settings.scss
https://projects.kodilla.com/browse/WDP200702-17
Dodałem RWD do sekcji New Furniture i ProductBox-ów.
=> WDP200702-17

src/styles/global.scss
https://projects.kodilla.com/browse/WDP200702-46
Dodany background-color w global.scss - body
=> WDP200702-46

src/App.js, src/components/features/NewFurniture/NewFurniture.js, src/components/features/NewFurniture/NewFurniture.module.scss, src/components/features/NewFurniture/NewFurnitureContainer.js, src/components/layout/MainLayout/MainLayout.js, src/components/layout/MainLayout/MainLayoutContainer.js, src/redux/deviceRedux.js, src/redux/initialState.js, src/redux/store.js, src/styles/settings.scss
https://projects.kodilla.com/browse/WDP200702-20
Zrobiłem reducer ustawiający rodzaj urządzenia w stanie aplikacji.
W New Furniture ustawiłem wyświetlanie ilości elementów w zależności od rodzaju urządzenia. 
Ustawiłem przywrócenie activePage na 0 przy zmianie urządzenia. Bo jak przechodziło się z mniejszego urządzenia na większe, a było się na stronie dalszej niż max liczba stron na większym urządzeniu, to nic się nie renderowało.
Poprawiłem kilka styli, żeby to pasowało do RWD, które już wcześniej robiłem
=> WDP200702-20

package.json, src/components/common/Swipeable/Swipeable.js, src/components/common/Swipeable/Swipeable.moule.scss, src/components/features/NewFurniture/NewFurniture.js, yarn.lock
https://projects.kodilla.com/browse/WDP200702-13?jql=key%20in%20(WDP200702-13)
- Dodałem komponent Swipeable wykorzystałem w nim react-swipeable,
- Dodałem 2 funkcje w NewFurniture: handleRightAction oraz handleLeftAction przekazywane do componentu Swipeable
- zmienianie activePage działa prawidłowo 
*? czy powinienem tworzyć animacje swipe, nie było to opisane w zadaniu ? *
=> Add Swipeable

src/components/common/HotDeal/HotDeal.js, src/components/common/HotDeal/HotDeal.module.scss, src/components/common/HotDeal/HotDealContainer.js, src/components/common/Swipeable/Swipeable.js, src/components/features/Promote/Promote.js, src/components/features/Promote/Promote.module.scss, src/components/features/Promote/PromoteContainer.js, src/components/views/Homepage/Homepage.js, src/redux/bannerRedux.js, src/redux/initialState.js, src/redux/store.js
- dodałem Promote component 
- dodałem HotDeal component
? czy zdjęcia to tego swipera po prawej stronie maja być pobierane z initial stora i czy to mają być jakieś konkretne zdjęcia któregoś z produktów na wyprzedaży czy po prostu jakieś przypadkowe ?
=> WDP-2007-02-22

src/components/features/ProductSearch/ProductSearch.module.scss, src/components/layout/MenuBar/MenuBar.js, src/components/layout/MenuBar/MenuBar.module.scss
CEL:
Zrobienie menu głownego responsywnym pod urządzenia mobilne (smartfony i tablety)
ZMIANY:
PLIK MENUBAR.JS:
-Zedytowałem strukture HTML: dodałem `input` i `label` aby rozwiązać problem rozwijanego menu bez użycia JS
-Dodałem bootstrapowe klasy dla divów: z polem search i z opcjami menu
PLIK MENUBAR.MODULE.SCSS:
-Dodałem style i media query aby nadać menu głównemu responsywny charakter;
PLIK PRODUCTSEARCH.MODULE.SCSS:
-Zmieniłem szerokość `inputow` aby komponenty nie rozjeżdzały się na urządzeniach o mniejszym rozmiarze
UWAGI:
-W pliku MenuBar.module.scc zastosowałem zmianę parametru `height`. Od 0 do 100vh.
-Wersja z zastosowaniem parametru: `max-height` wygląda wizualnie ładniej ale nie przykrywa całej strony.
JIRA:
https://projects.kodilla.com/browse/WDP200702-14
=> WDP200702-14

src/components/features/Blog/Blog.js, src/components/features/Blog/Blog.module.scss, src/components/features/BlogPost/BlogPost.js, src/components/features/BlogPost/BlogPost.module.scss, src/components/features/BlogPost/BlogPostContainer.js, src/components/views/Homepage/Homepage.js, src/redux/initialState.js
Add Blog and BlogPost components
=> WDP200702-37 

.stylelintrc.json, package-lock.json, package.json, src/components/common/Button/Button.module.scss, src/components/common/FeatureBox/FeatureBox.module.scss, src/components/common/HotDeal/HotDeal.module.scss, src/components/common/ProductBox/ProductBox.module.scss, src/components/common/PromotionItem/PromotionItem.module.scss, src/components/common/Stars/Stars.module.scss, src/components/features/Brands/Brands.module.scss, src/components/features/CompareList/CompareList.module.scss, src/components/features/FeatureBoxes/FeatureBoxes.module.scss, src/components/features/NewFurniture/NewFurniture.module.scss, src/components/features/ProductSearch/ProductSearch.module.scss, src/components/features/Promote/Promote.module.scss, src/components/features/PromotionBox/PromotionBox.module.scss, src/components/layout/CompanyClaim/CompanyClaim.module.scss, src/components/layout/Footer/Footer.module.scss, src/components/layout/Header/Header.module.scss, src/components/layout/MenuBar/MenuBar.module.scss, src/components/layout/TopBar/TopBar.module.scss, src/styles/settings.scss
https://projects.kodilla.com/browse/WDP200702-43
=> Add package stylelint to project

src/components/features/Feedback/Feedback.js, src/redux/initialState.js
Dodanie Swipable do feedback, dodałem również id do feedbacks żeby zachować spójność z innymi komponentami
https://projects.kodilla.com/browse/WDP200702-34
=> Add swipable to Feedback

src/components/features/Blog/Blog.module.scss, src/components/features/BlogPost/BlogPost.module.scss
=> WDP200702-38 

src/components/features/PromotionBox/PromotionBox.module.scss
=> WDP200702-26 

src/components/features/CompareList/CompareList.module.scss, src/components/layout/Footer/Footer.module.scss, src/components/layout/MainLayout/MainLayout.js
Change styles in CompareList component
=> WDP200702-48

package.json, src/components/common/FeatureBox/FeatureBox.js, src/components/common/Stars/Stars.js, src/components/features/BlogPost/BlogPost.js, src/components/features/Feedback/Feedback.js, src/components/features/Gallery/Gallery.js, src/components/features/NewFurniture/NewFurniture.js, src/components/features/ProductSearch/ProductSearch.js, src/components/features/Promote/Promote.js, src/components/layout/CompanyClaim/CompanyClaim.js, src/components/layout/Footer/Footer.js, src/components/layout/MenuBar/MenuBar.js, src/components/layout/TopBar/TopBar.js
Resolve issues from eslint, add slash to href
Wyczytalem ze nie do konca sie da disable dac na wbudowanej konfiguracji zasad eslinta w create-react-app, jedyne co moge zrobic to zastosowac sie do uwag ktore dawaly bledy, a bledy byly przez to ze powinniej byc slash przy a href, powinno byc tak href='/#'. W kazdym razie zmienilem to tak jak powinno byc i czekam na fdbk czy to jest okej
=> WDP200702-35

src/components/features/Feedback/Feedback.js, src/components/features/Feedback/Feedback.module.scss
https://projects.kodilla.com/browse/WDP200702-50
- dodałem połączenie pomiędzy kropkami a sliderem
=> WDP200702-50

src/components/features/Gallery/Gallery.js, src/components/features/Gallery/Gallery.module.scss, src/components/features/Gallery/GalleryContainer.js, src/redux/categoriesRedux.js, src/redux/initialState.js, src/styles/settings.scss
CEL:
FUNKCJONALNOŚĆ GALERII
UWAGI:
Prosiłbym o informację czy mechanika działania (zmiana kategorii oraz wybór miniatur z fade) spełnia wymagania projektu.
Swipe - element utracił funkcjonalność - zostanie poprawiony dzisiaj
JIRA: 
https://projects.kodilla.com/browse/WDP200702-28
=> WDP200702-28

src/App.js, src/components/common/ProductBox/ProductBox.js, src/components/views/NotFound/NotFound.js, src/components/views/NotFound/NotFound.module.scss, src/components/views/ProductPage/ProductPage.js, src/components/views/ProductPage/ProductPageContainer.js, src/redux/productsRedux.js, yarn.lock
Widok produktu - funkcjonalność - przejście do widoku produktu
https://projects.kodilla.com/browse/WDP200702-39
nowy component NotFound renderuje się gdy ściezka jest nie poprawna
klikniecie w obrazek lup nazwę produktu przenosi do widoku danego produktu
=> Wdp200702 39

src/components/layout/CompanyClaim/CompanyClaim.js
Link do strony głównej w Logo sklepu.
https://projects.kodilla.com/browse/WDP200702-41
=> WDP200702-41 Add link to the main page in logo

package-lock.json, package.json, src/components/views/ProductPage/ProductPage.js, src/components/views/ProductPage/ProductPage.module.scss
https://projects.kodilla.com/browse/WDP200702-40
Dodanie layoutu produktu
=> Wdp200702 40

src/components/features/Promote/Promote.js, src/components/features/Promote/Promote.module.scss
miałem problem z konfliktami więc utworzyłme nowy branch
https://projects.kodilla.com/browse/WDP200702-24
=> Add Rwd to component
